# Generated by Django 5.0.7 on 2024-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_the_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time_now', models.DateTimeField(auto_now_add=True)),
                ('date_time_target', models.DateTimeField()),
                ('description', models.TextField(max_length=10000)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_time_target'],
            },
        ),
    ]
